/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Eduardo
 */
public class Administrador extends javax.swing.JFrame {

    GridBagLayout layout =  new GridBagLayout();
    RegistrarUsuarioP pregistrar;
    ModificarUsuarioP pmodificar;
    ListarUsuariosP plistado;
    /**
     * Creates new form Administrador
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public Administrador() throws ClassNotFoundException, SQLException {
        this.pregistrar = new RegistrarUsuarioP();
        this.pmodificar = new ModificarUsuarioP();
        this.plistado =  new ListarUsuariosP();
        initComponents();
       this.getContentPane().setBackground(Color.WHITE);
         this.setLocationRelativeTo(null);
         jPAdministrador.setLayout(layout);
         GridBagConstraints c = new GridBagConstraints();
         c.gridx = 0;
         c.gridy = 0;
         jPAdministrador.add(pregistrar);
         c.gridx = 0;
         c.gridy = 0 ;
         jPAdministrador.add(pmodificar);
                c.gridx = 0;
         c.gridy = 0 ;
         jPAdministrador.add(plistado);
         pregistrar.setVisible(false);
         pmodificar.setVisible(false);
         plistado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPAdministrador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        MenuCrearUsuario = new javax.swing.JMenuItem();
        MenuLIstarUsuarios = new javax.swing.JMenuItem();
        MenuModificarUsuario = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuGenerarBI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(1241, 730));

        jPAdministrador.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPAdministradorLayout = new javax.swing.GroupLayout(jPAdministrador);
        jPAdministrador.setLayout(jPAdministradorLayout);
        jPAdministradorLayout.setHorizontalGroup(
            jPAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPAdministradorLayout.setVerticalGroup(
            jPAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Iconocompleto.png"))); // NOI18N

        jMenu4.setText("Usuario");
        jMenu4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        MenuCrearUsuario.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        MenuCrearUsuario.setText("Registar Usuario");
        MenuCrearUsuario.setActionCommand("Registrar Usuario");
        MenuCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearUsuarioActionPerformed(evt);
            }
        });
        jMenu4.add(MenuCrearUsuario);

        MenuLIstarUsuarios.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        MenuLIstarUsuarios.setText("Listar Usuarios");
        MenuLIstarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLIstarUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(MenuLIstarUsuarios);

        MenuModificarUsuario.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        MenuModificarUsuario.setText("Modificar Usuario");
        MenuModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuModificarUsuarioActionPerformed(evt);
            }
        });
        jMenu4.add(MenuModificarUsuario);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Reporte");
        jMenu5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        MenuGenerarBI.setText("Generar BI");
        MenuGenerarBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGenerarBIActionPerformed(evt);
            }
        });
        jMenu5.add(MenuGenerarBI);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 1092, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearUsuarioActionPerformed
       /*RegistarUsuario registrar = null;
        try {
            registrar = new RegistarUsuario();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
          registrar.setVisible(true);*/
        
         pregistrar.setVisible(true);
          pmodificar.setVisible(false);
          plistado.setVisible(false);
          
          
    }//GEN-LAST:event_MenuCrearUsuarioActionPerformed

    private void MenuGenerarBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGenerarBIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuGenerarBIActionPerformed

    private void MenuLIstarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLIstarUsuariosActionPerformed
         
         /*ListarUsuarios listar = null;
        try {
            listar = new ListarUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
         listar.setVisible(true);*/
          pregistrar.setVisible(false);
          pmodificar.setVisible(false);
          plistado.setVisible(true);
         
    }//GEN-LAST:event_MenuLIstarUsuariosActionPerformed

    private void MenuModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuModificarUsuarioActionPerformed
       /* ModificarUsuario modificar = null;
        try {
            modificar = new ModificarUsuario();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        modificar.setVisible(true);*/
       pmodificar.setVisible(true);
       pregistrar.setVisible(false);
       plistado.setVisible(false);
    }//GEN-LAST:event_MenuModificarUsuarioActionPerformed
 @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Img/iconoV2.png"));


        return retValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Administrador().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCrearUsuario;
    private javax.swing.JMenuItem MenuGenerarBI;
    private javax.swing.JMenuItem MenuLIstarUsuarios;
    private javax.swing.JMenuItem MenuModificarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPAdministrador;
    // End of variables declaration//GEN-END:variables
}
