/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class ListarUsuariosP extends javax.swing.JPanel {
   DefaultTableModel ListarTablaUsuarios;
    /**
     * Creates new form ListarUsuariosP
     */
    public ListarUsuariosP() throws SQLException, ClassNotFoundException {
         ListarTablaUsuarios = new DefaultTableModel(null,getColumna());
        setFilas();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableListarUsuarios = new javax.swing.JTable();
        BtnAceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 18))); // NOI18N

        TableListarUsuarios.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TableListarUsuarios.setModel(ListarTablaUsuarios);
        jScrollPane1.setViewportView(TableListarUsuarios);

        BtnAceptar.setBackground(new java.awt.Color(153, 153, 255));
        BtnAceptar.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public String [] getColumna(){
        String columna[]= new String[]{"RUT","NOMBRE","APELLIDO PATERNO","APELLIDO MATERNO","CORREO ELECTRONICO","DIRECCION","TELEFONO","ROL","COMUNA"};
        return columna;
    }
    
    public void setFilas() throws SQLException, ClassNotFoundException{
        
        
        Connection conn = null;
        Conexion conexion = new Conexion();
        conn=conexion.getConnection();
        Statement sentencia = null;
        ResultSet rs = null;
        String tipo=null;
        String query =  "select U.RUT_USUARIO,U.NOMBRE_USUARIO,U.APEPA_USUARIO,U.APEMA_USUARIO,U.CORREO_USUARIO,U.DIRECCION_USUARIO,U.TELEFONO_USUARIO,R.NOMBRE_TIPOUSUARIO,C.NOMBRE_COMUNA\n" +
"FROM USUARIO U , TIPOUSUARIO R, COMUNA C \n" +
"WHERE u.id_tipousuario = r.id_tipousuario AND u.id_comuna = c.id_comuna ";
        sentencia =conn.createStatement();
        rs = sentencia.executeQuery(query);
       
        Object datos []=new Object[9];
        
        while(rs.next()){
            for (int i = 0; i < 9; i++) {
                datos[i]= rs.getObject(i+1);
            }
            ListarTablaUsuarios.addRow(datos);
        }
        rs.close();
    }
    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
     this.setVisible(false);
    }//GEN-LAST:event_BtnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    public javax.swing.JTable TableListarUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
